# Build website and save it on gh-pages branch
name: build-and-save-website

# Only run this when the main branch is changed
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:

# This job installs dependencies, builds the website and pushes it to `gh-pages`
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install '.[docs]'

      - name: Build the site
        run: |
          cd docs
          sphinx-build -nW --keep-going -b html .  _build

      - name: Save to gh-pages
        # # if: ${{ github.ref == 'refs/heads/main' }}
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build
